# Generated by Django 5.0 on 2023-12-11 09:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('authors', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('publisher', models.CharField(max_length=255)),
                ('number_of_pages', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(max_length=255)),
                ('checked_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
