# Generated by Django 5.0 on 2023-12-12 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_checkoutbooks_checkoutbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutbook',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
