# Generated by Django 5.0 on 2023-12-12 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_checkoutbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 11, 4, 7, 329456, tzinfo=datetime.timezone.utc)),
        ),
    ]
