# Generated by Django 5.0 on 2023-12-12 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_id_checkoutbook_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 11, 15, 40, 74694, tzinfo=datetime.timezone.utc)),
        ),
    ]
