# Generated by Django 5.0 on 2023-12-12 11:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_checkoutbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutbook',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='checkoutbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 11, 33, 45, 73493, tzinfo=datetime.timezone.utc)),
        ),
    ]
