# Generated by Django 5.0 on 2023-12-19 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_checkoutbook_options_checkoutbook_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checked_out',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 0, 45, 23, 714785, tzinfo=datetime.timezone.utc)),
        ),
    ]
