# Generated by Django 5.0 on 2023-12-19 00:55

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_checked_out_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 0, 55, 23, 751876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ReserveBook',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
