# Generated by Django 5.0 on 2023-12-19 01:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_checkoutbook_due_date_reservebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 1, 8, 22, 547947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
