# Generated by Django 5.0 on 2023-12-19 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_checkoutbook_due_date_alter_reservebook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutbook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 1, 9, 19, 922731, tzinfo=datetime.timezone.utc)),
        ),
    ]
